name: 'Resourcely Change Management'
description: 'Scan the pr against all related guardrails'
inputs:
  gh_access_token:
    description: 'access token to access github'
    required: false
  tf_api_token:
    description: 'terraform cloud api token; if not specified, then will not go to terraform cloud to fetch the plan'
    required: false
  resourcely_api_token:
    description: 'api to access resourcely api'
    required: true
  resourcely_api_host:
    description: 'url for the resoucely api'
    required: false
  tf_plan_directory:
    description: 'directory to hold all the terraform plan'
    required: false
    default: 'tf-plan-files'
runs:
  using: "composite"
  steps:
    - name: Create directory for plan files if not present
      shell: bash
      run: |
        if [[ -d "${{ inputs.tf_plan_directory }}" ]]; then
          echo "Directory already exist"
        else
          mkdir ${{ inputs.tf_plan_directory }}
        fi
      
    - name: Wait for checks to complete
      shell: bash
      if:  ${{ inputs.tf_api_token != '' }}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        docker pull ghcr.io/resourcely-inc/wait-for-terraform-plan:latest
        ENCODED_GITHUB_CONTEXT=$(echo -n "$GITHUB_CONTEXT" | base64)
        docker run \
          -e GITHUB_TOKEN="${{ inputs.gh_access_token }}" \
          -e GITHUB_CONTEXT="${ENCODED_GITHUB_CONTEXT}" \
          -e TF_API_TOKEN="${{ inputs.tf_api_token }}" \
          -e RESOURCELY_API_HOST="${{ inputs.resourcely_api_host }}" \
          -e RESOURCELY_API_TOKEN="${{ inputs.resourcely_api_token }}" \
          -v "$(pwd)/${{ inputs.tf_plan_directory }}:/app/tf-plan-files" \
          ghcr.io/resourcely-inc/wait-for-terraform-plan:latest

    - name: Evaluate Code With Resourcely Guardrails
      shell: bash
      if: success()
      run: |
        docker pull ghcr.io/resourcely-inc/resourcely-cli:latest
        plans=$(ls -1 ${{ inputs.tf_plan_directory }}/plan* | sed "s|^|/data/|" | tr '\n' ',' | sed 's/,$//')
        docker run --rm \
          -v "$(pwd)/${{ inputs.tf_plan_directory }}:/data/${{ inputs.tf_plan_directory }}" \
          -e RESOURCELY_API_TOKEN="${{ inputs.resourcely_api_token }}" \
          -e GITHUB_TOKEN="${{ inputs.gh_access_token }}" \
          ghcr.io/resourcely-inc/resourcely-cli:latest evaluate \
          --api_host "${{ inputs.resourcely_api_host }}" \
          --vcs github \
          --change_request_url "${{ github.event.pull_request.html_url }}" \
          --change_request_sha "${{ github.event.pull_request.head.sha }}" \
          "${plans}"